config/routes.rb
Myagenda::Application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :agendas
  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.has_role? "administrator"
      can :manage, :all      
    else
      can :manage, Agenda    
    end
    
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/agenda.rb
class Agenda < ActiveRecord::Base
	belongs_to :user
	mount_uploader :attachment, AttachmentUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #, :confirmable

  has_many :agendas 
  belongs_to :role
  before_create :set_default_role

  # @parama = string (administrator or general_user)
  def has_role?(role)
   	self.role.name == role   	
  end

  private
    def set_default_role
      self.role ||= Role.find_by_name('general_user')
    end
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  before_action :set_agenda, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]  
  before_filter :check_owner, except: [:show, :index, :new, :create]

  load_and_authorize_resource
  skip_load_resource :only => [:create]
  # GET /agendas
  # GET /agendas.json
  def index
    @agendas = current_user.agendas.all
  end

  # GET /agendas/1
  # GET /agendas/1.json
  def show    
  end

  # GET /agendas/new
  def new
    @agenda = Agenda.new
  end

  # GET /agendas/1/edit
  def edit
    # testing purpose, will be removed after get real module
    # authorize! :edit, @agenda, :message => "You don't have permission"
  end

  # POST /agendas
  # POST /agendas.json
  def create
    @agenda = current_user.agendas.new(agenda_params)

    respond_to do |format|
      if @agenda.save
        format.html { redirect_to @agenda, notice: 'Agenda was successfully created.' }
        format.json { render action: 'show', status: :created, location: @agenda }
      else
        format.html { render action: 'new' }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agendas/1
  # PATCH/PUT /agendas/1.json
  def update
    respond_to do |format|
      if @agenda.update(agenda_params)
        format.html { redirect_to @agenda, notice: 'Agenda was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendas/1
  # DELETE /agendas/1.json
  def destroy
    @agenda.destroy
    respond_to do |format|
      format.html { redirect_to agendas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agenda
      @agenda = Agenda.find(params[:id])
    end

    def check_owner
      if @agenda.user.id != current_user.id        
        redirect_to agendas_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agenda_params
      params.require(:agenda).permit(:title, :when, :place, :description, :attachment)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # for custom field on registration 1
  # before_action :configure_devise_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|    
    redirect_to root_url, :alert => exception.message
  end

 # for custom field on registration 2
 #  protected

 #    def configure_devise_permitted_parameters
 #      registration_params = [:full_name, :email, :password, :password_confirmation]

 #      if params[:action] == 'update'
 #        devise_parameter_sanitizer.for(:account_update) { 
 #          |u| u.permit(registration_params << :current_password)
 #        }
 #      elsif params[:action] == 'create'
 #        devise_parameter_sanitizer.for(:sign_up) { 
 #        |u| u.permit(registration_params) 
 #      }
 #   	end
 # 	  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@users_count = User.all.count
		@agendas = Agenda.all
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!  
  load_and_authorize_resource
  skip_authorize_resource :only => :show  

  def index
    @users = User.all    
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_url, :alert => "Access denied."
    end
  end

end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/agendas/_form.html.erb
<%= form_for @agenda, html: {multipart: true} do |f| %>
  <% if @agenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agenda.errors.count, "error") %> prohibited this agenda from being saved:</h2>

      <ul>
      <% @agenda.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :when %><br>
    <%= f.datetime_select :when %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
   <div class="field">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agendas/edit.html.erb
<h1>Editing agenda</h1>

<%= render 'form' %>

<%= link_to 'Show', @agenda %> |
<%= link_to 'Back', agendas_path %>

app/views/agendas/index.html.erb
<h1>Listing agendas</h1>

<table>
  <thead>
    <tr>
      <th>No. </th>
      <th>Title</th>
      <th>When</th>
      <th>Place</th>
      <th>Description</th>
      <th>Owner</th>
      <th>Link</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @agendas.each_with_index do |agenda, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= agenda.title %></td>
        <td><%= agenda.when %></td>
        <td><%= agenda.place %></td>        
        <td><%= agenda.description %></td>
        <td><%= agenda.user.email %></td>
        <td><%= link_to "Download Picture", agenda.attachment.url %></td>
        <td><%= link_to 'Show', agenda %></td>
        <td><%= link_to 'Edit', edit_agenda_path(agenda) %></td>
        <td><%= link_to 'Destroy', agenda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agenda', new_agenda_path %>

app/views/agendas/new.html.erb
<h1>New agenda</h1>

<%= render 'form' %>

<%= link_to 'Back', agendas_path %>

app/views/agendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @agenda.title %>
</p>

<p>
  <strong>When:</strong>
  <%= @agenda.when %>
</p>

<p>
  <strong>Place:</strong>
  <%= @agenda.place %>
</p>

<p>
  <strong>Description:</strong>
  <%= @agenda.description %>
</p>

<%= link_to 'Edit', edit_agenda_path(@agenda) %> |
<%= link_to 'Back', agendas_path %>

app/views/home/index.html.erb
<!-- if user not signed in, render partial view contain sign up and login -->
<!-- if user signed in, root to agendas... -->


	<div id="newest-agenda">
		<% @agendas.each do |agenda| %>
		<div class="item">
			<h4><%= agenda.title %></h4>
			<small>When: <i> <%= agenda.when.to_formatted_s(:long_ordinal) %></i>. Place <i><%= agenda.place %></i></small>
			<p><%= agenda.description %></p>
			<code>By: <%= agenda.user.email %></code>
		</div>
		<% end %>
	</div>	
	


<% if user_signed_in? %>	

	<div id="user-profile">
		Hello, Thanks for coming back.<br>
		Your last login at <%= current_user.last_sign_in_at %>.<br>
		<%= link_to "Edit Profile", edit_user_registration_path %>
	</div>

<% else %>

	<div id="registration-form">
		<h2 class="headline">Sign up for free. <br><small><i><%= pluralize(@users_count, 'person') %> around the world have joined! This is your turn!</i></small></h2>

		<%= form_for User.new, :url => user_registration_path do | f |%>
			<div class="field">
				<%= f.label :email %> 
				<%= f.text_field :email %>
			</div>

			<div class="field">
				<%= f.label :password %>
				<%= f.password_field :password %>
			</div>

			<div class="field">
				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation %>
			</div>

			<div class="field">
				<%= f.submit "Sign up" %>		
			</div>

		<% end %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myagenda</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<style type="text/css">
 	#container { 
 	  width: 960px; 
 	  margin: 0 auto; 
 	  margin-top: 20px; 
 	}

 	#header { 
 	  width: 100%; 
 	  margin-bottom: 10px; 
 	  padding-bottom: 10px; 
 	  border-bottom: 1px solid #ccc; 
 	  overflow: hidden;
 	}

 	#logo {
 	  float:left;
 	  margin-right: 25px;
 	  font-size: 24px;
 	  height: 26px;
 	}

 	#logo a {
 	  font-style: italic; 
 	  text-decoration: none;
 	}

 	#header .menu {
 	  float: right; 
 	  text-align: right;
 	  overflow: hidden; 
 	  width: 80%;

 	}

 	#newest-agenda {
 	  width: 60%;	
 	  float: left;
 	}

 	#newest-agenda .item {
 	  border-bottom: 1px solid #eee;
 	  margin-bottom: 10px;
 	  padding: 10px 20px;
 	}

 	.item h4 {
 		margin-top: 0px;
 	}

 	#registration-form, #user-profile {
 	  width: 33%;
 	  float: right;
 	  padding: 10px 0 10px 20px;
 	  text-align: right;
 	  border-left: 1px solid #eee;
 	}

 	#registration-form .headline{
 		line-height: 20px;
 	}

 	.menu-left {
 	  float: left;
 	}

 	.menu-right {
 	  float: right;
 	}

 	.alert {
 	  padding: 10px; 
 	}

 	.alert.grey {
 	  background-color: #eee;
 	}

 	.alert.red {
 	  background-color: #FF8080;
 	}


</style>
<body>

	<div id="container">

		<div id="header">
			<div id="logo">
				<%= link_to "MyAgenda",  root_path %>	
			</div>
			<div class="menu">
				<% if user_signed_in? %>
					<div class="menu-left">
						<%= link_to "+ New Agenda",  new_agenda_path %> | 
					 	<%= link_to "Agendas",  agendas_path %>
					 	<% if can? :read, @users %>
						  | <%= link_to "Users", users_path %>
						<% end %>
					</div>	
					<div class="menu-right">	
						<a><%= current_user.email %></a> | 
					 	<%= link_to "Log out",  destroy_user_session_path, method: :delete %>		
					</div>			 
				<% else %>
					<%= form_for(:user, :url => session_path(:user)) do |f| %>			  
					  <%= f.label "Login:" %>
					  <%= f.text_field :email %>
					  <%= f.password_field :password %>
					  <%= f.check_box :remember_me %>
					  <%= f.label :remember_me %>
					  <%= f.submit 'Sign in' %>
					  <%= link_to "Forgot your password?", new_password_path(:user) %>
					<% end %>	
				<% end %>	
			</div>
		</div>

		<% if notice %> <p class="alert grey"><%= notice %></p> <% end %>
		<% if alert %> <p class="alert red"><%= alert %></p> <% end %>

		<%= yield %>

	</div>
</body>
</html>

app/views/users/index.html.erb
<% @users.each do | u | %>
	<a href="#"><%= u.email %></a><br>
<% end %>

app/views/users/show.html.erb
<a href="#"><%= @user.email %></a><br>
Your last login at <%= current_user.last_sign_in_at %>.<br>
Your role is: <%= @user.role.name %>